Sleep in function app function check so we don't error prematurely (#225)
---------

Co-authored-by: Samuel Aquino <saquino@flexion.us>
Co-authored-by: jcrichlake <145698165+jcrichlake@users.noreply.github.com>
Co-authored-by: Bella L. Quintero <96704946+pluckyswan@users.noreply.github.com>

diff --git a/.github/workflows/functions-deploy.yml b/.github/workflows/functions-deploy.yml
--- a/.github/workflows/functions-deploy.yml
+++ b/.github/workflows/functions-deploy.yml
@@ -78,10 +78,25 @@ jobs:
 
       - name: 'Retrieve Azure FunctionApp loaded Functions'
         run: |
-          FUNCTION_LIST=$(az functionapp function list -g "csels-rsti-${{ inputs.TF_ENVIRONMENT }}-moderate-rg" -n "polling-function-${{ inputs.TF_ENVIRONMENT }}")
-          if [[ $FUNCTION_LIST == *"[]"* ]]; then 
-            FAIL=true
-          fi
+          MAX_TIME=300   # Maximum time in seconds (5 minutes)
+          INTERVAL=5     # Check every 5 seconds
+          ELAPSED_TIME=0
+          FAIL=true
+
+          # Loop until the function is created or the maximum time is reached
+          while [ $ELAPSED_TIME -lt $MAX_TIME ]; do
+            FUNCTION_LIST=$(az functionapp function list -g "csels-rsti-${{ inputs.TF_ENVIRONMENT }}-moderate-rg" -n "polling-function-${{ inputs.TF_ENVIRONMENT }}")
+            if [[ $FUNCTION_LIST != *"[]"* ]]; then
+              echo "Function found after $ELAPSED_TIME seconds"
+              FAIL=false
+              break
+            fi
+            # If we don't have a function yet, sleep INTERVAL seconds and increment elapsed time
+            echo "Function not found, sleeping $INTERVAL seconds. $ELAPSED_TIME seconds have elapsed so far"
+            sleep $INTERVAL
+            ELAPSED_TIME=$((ELAPSED_TIME + INTERVAL))
+          done
+
           echo "FAIL=$FAIL" >> $GITHUB_OUTPUT
         id: getFunctionList
 
@@ -89,4 +104,4 @@ jobs:
         if: steps.getFunctionList.outputs.FAIL == 'true'
         run: |
           echo 'Azure FunctionApp Function is empty'
-          exit 1 
+          exit 1
